version: "3.7"

services:
    web:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8080:80
        networks:           # nginx is connected to both networks
            - app1_net
            - app2_net
            
    app1:
        image: httpd:latest
        networks:
            - app1_net          # app1 is connected only to app1_net network

    app2:
        image: httpd:latest
        networks:
            - app2_net          # app2 is connected only to app2_net network 