version: "3"

services:
    db:
        image: mysql:5.7
        restart: always
        container_name: myphpapp-db
        environment:
            MYSQL_ROOT_PASSWORD: somepass
            MYSQL_DATABASE: somedatabase
        volumes:
            - $PWD/data/:/var/lib/mysql

    dbclient:
        image: mysql:5.7
        depends_on:
            - db
        command: mysql -uroot -psomepass -hdb