version: "3"

services:
    phpapp:
        build:
            context: ./
            dockerfile: Dockerfile
        image: phpapp:123           #this will be the image name:tag
        ports:
            - "8080:80"
        volumes:
            - "./:/var/www/html"
        #   - "$PWD:/var/www/html"
        container_name: my-php-app  #this will be the container