version: "3"

services:
    db:
        image: mysql:5.7
        restart: always
        container_name: myphpapp-db
        environment:
            MYSQL_ROOT_PASSWORD: somepass
            MYSQL_DATABASE: somedatabase
        volumes:
            - $PWD/data/:/var/lib/mysql

    dbclient:
        #image: mysql:5.7
        build:
            context: ./
            dockerfile: Dockerfile
            
        depends_on:
            - db
        #command: ["/wait-for-it.sh", "db:3306", "--", "python", "app.py"]
        #command: mysql -uroot -psomepass -hdb
        command: ["/home/wait-for-it.sh", "db:3306", "--", "mysql", "-uroot", "-psomepass", "-hdb"]